# -*- coding: utf-8 -*-
"""Configuración de Firebase

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PgC7-0aV4XBcJPkACvERNuK4quYbBlG2
"""

import streamlit as st
import firebase_admin
from firebase_admin import credentials, firestore

def init_firebase():
    """
    Inicializa la conexión con Firebase usando las credenciales de st.secrets.
    Devuelve una instancia del cliente de Firestore.
    """
    if not firebase_admin._apps:
        creds_dict = st.secrets["firebase"]
        creds = credentials.Certificate(creds_dict)
        firebase_admin.initialize_app(creds)

    return firestore.client()